# Generated by Django 3.1.3 on 2020-11-08 19:30

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(upload_to=apps.products.models.upload_location, verbose_name='photo')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='minimum bid amount')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='maximum bid amount')),
                ('expiry_date', models.DateTimeField(default=apps.products.models.default_expirydate, verbose_name='bid closing date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
            },
        ),
    ]
