# Generated by Django 3.1.3 on 2020-11-07 20:33

import apps.products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to=apps.products.models.upload_location, verbose_name='Photo')),
                ('min_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Minimum Bid Amount')),
                ('max_price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Maximum Bid Amount')),
                ('expiry_date', models.DateTimeField(default=apps.products.models.default_expirydate, verbose_name='Bid Submission Expiry Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
