# Generated by Django 3.1.3 on 2020-11-08 17:28

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201108_0502'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiry_date',
            field=models.DateTimeField(default=apps.products.models.default_expirydate, verbose_name='bid closing date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to=apps.products.models.upload_location, verbose_name='photo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='max_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='maximum bid amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='minimum bid amount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=150, verbose_name='name'),
        ),
    ]
